### ISSUE TITLE
Long filenames can break FTP transport

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-deposit-services#267]
`
13:13:54.491 [   pool-174-thread-1] ERROR [        ArchivingPackageStream] - Error encountered when writing the package stream.
java.lang.RuntimeException: file name 'fp4-asheville-04-ei100-pyrocathd_1_1_100-taken20190627_dev20190629-in74deg_out76_12min30s-2invmin (2).tif' is too long ( > 100 bytes)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.handleLongName(TarArchiveOutputStream.java:668)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:343)
	at org.dataconservancy.pass.deposit.assembler.shared.DefaultStreamWriterImpl.writeResource(DefaultStreamWriterImpl.java:233)
	at org.dataconservancy.pass.deposit.assembler.shared.DefaultStreamWriterImpl.writeResource(DefaultStreamWriterImpl.java:178)
	at org.dataconservancy.pass.deposit.assembler.shared.DefaultStreamWriterImpl.assembleResource(DefaultStreamWriterImpl.java:252)
	at org.dataconservancy.pass.deposit.assembler.shared.DefaultStreamWriterImpl.lambda$start$0(DefaultStreamWriterImpl.java:108)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.dataconservancy.pass.deposit.assembler.shared.DefaultStreamWriterImpl.start(DefaultStreamWriterImpl.java:108)
	at org.dataconservancy.pass.deposit.assembler.shared.CallableStreamWriter.call(CallableStreamWriter.java:69)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
